# %% Definir funciones
import numba as nb
import numpy as np
from scipy.constants import G as _G
from scipy.optimize import fsolve
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import time


def moment_of_inertia_two_parallelepipeds_z(
    density,
    lx,
    ly,
    lz,
    r,
):
    """
    Moment of inertia around the global z-axis for
    two identical rectangular parallelepipeds.
    """
    mass = density * lx * ly * lz
    # Intrinsic inertia of one prism around its own COM
    Iz_cm = (mass / 12.0) * (lx**2 + ly**2)

    # Parallel axis theorem
    Iz_one = Iz_cm + mass * r**2

    # Two identical prisms
    Iz_total = 2.0 * Iz_one

    return Iz_total


@nb.njit(fastmath=True)
def gravitational_field_parallelepiped(
    xp, yp, zp, xc, yc, zc, lxs, lys, lzs, density, G
):
    """
    Optimized field generated by source parallelepiped.
    """
    x1 = xc - lxs / 2.0
    x2 = xc + lxs / 2.0
    y1 = yc - lys / 2.0
    y2 = yc + lys / 2.0
    z1 = zc - lzs / 2.0
    z2 = zc + lzs / 2.0

    # Using tuples instead of np.array avoids heap allocation overhead in Numba
    xs_val = (x1 - xp, x2 - xp)
    ys_val = (y1 - yp, y2 - yp)
    zs_val = (z1 - zp, z2 - zp)

    rs = np.array([xc, yc, zc])
    rt = np.array([xp, yp, zp])
    r_rel = rt - rs

    F = -r_rel / np.linalg.norm(r_rel) ** 3
    F *= G * density * 4 / 3 * np.pi * lxs**3
    gx, gy, _ = F
    return gx, gy


@nb.njit(parallel=True, fastmath=True)
def calculate_torque_z(
    phi,
    r,
    lxs_p,
    lys_p,
    lzs_p,
    density_p,
    xc,
    yc,
    zc,
    lxs,
    lys,
    lzs,
    density,
    G,
    nodes,
    weights,
):
    """
    Calculates the z-axis torque on a transformed probe parallelepiped using
    Gauss-Legendre integration. Fully Numba JIT-able.
    """
    cos_phi = np.cos(phi)
    sin_phi = np.sin(phi)

    # Semi-axes sizes used to scale nodes/weights from [-1, 1] to the block limits
    hx = lxs_p / 2.0
    hy = lys_p / 2.0
    hz = lzs_p / 2.0

    num_pts = len(nodes)
    total_torque = 0.0

    # Parallelize the outer loop across available CPU cores
    for i in nb.prange(num_pts):
        u = hx * nodes[i]
        w_i = weights[i] * hx

        for j in range(num_pts):
            v = hy * nodes[j]
            w_j = weights[j] * hy

            for k in range(num_pts):
                w = hz * nodes[k]
                w_k = weights[k] * hz

                # 1. Rigid Transformation: Translate along x by 'r', then rotate by 'phi'
                # (Local block center starts at the origin)
                xp = (u + r) * cos_phi - v * sin_phi
                yp = (u + r) * sin_phi + v * cos_phi
                zp = w

                # 2. Get the gravitational field components at this point
                gx, gy = gravitational_field_parallelepiped(
                    xp, yp, zp, xc, yc, zc, lxs, lys, lzs, density, G
                )

                # 3. Torque density around z-axis: dTau = (x * g_y - y * g_x) * dm
                torque_density = (xp * gy - yp * gx) * density_p

                # 4. Accumulate weighted contribution
                total_torque += w_i * w_j * w_k * torque_density

    return total_torque


# %%
k = 0.0001262092012659314
r = 37e-2
d = 8e-2
lxs_p, lys_p, lzs_p = 14.04e-2, 3.48e-2, 7e-2
lxs, lys, lzs = 6e-2, 5.05e-2, 10.15e-2
xc, yc, zc = r, d, 0
# density = 11340
density = 3.80 / (lxs_p * lys_p * lzs_p)
# delta_phi_deg = 0.012287426944132207
delta_phi_deg = 0.05
delta_phi = delta_phi_deg / 180 * np.pi
# Integration parameters
N_order = 10
nodes, weights = np.polynomial.legendre.leggauss(N_order)

tau_con_G_1 = calculate_torque_z(
    delta_phi,
    r,
    lxs_p,
    lys_p,
    lzs_p,
    density,
    xc,
    yc,
    zc,
    lxs,
    lys,
    lzs,
    density,
    1,
    nodes,
    weights,
)

G = k * delta_phi / tau_con_G_1

diff_rel = np.abs((G - _G) / (G + _G) * 2)
print("G da:")
print("tatan tatan...")
time.sleep(2)
print(G)
time.sleep(1)
print("Debería dar ...")
time.sleep(2)
print(_G)
if diff_rel < 0.05:
    print(f"Diferencia relativa {diff_rel * 100}% < 5%, felicitaciones!")
else:
    print(f"Diferencia relativa {diff_rel * 100}% >= 5%, son unos fracasados :(")
# %%
