# %% Definir funciones
import numpy as np
from numba import njit
from scipy.integrate import solve_ivp, tplquad
from scipy.optimize import fsolve
import matplotlib.pyplot as plt


# @njit
def _safe_log(a, b):
    return np.log(a + b) - np.log(a - b)


# @njit
def rotation_matrix_z(angle):
    c = np.cos(angle * np.pi / 180)
    s = np.sin(angle * np.pi / 180)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


# @njit
def rotation_matrix_x(angle):
    c = np.cos(angle * np.pi / 180)
    s = np.sin(angle * np.pi / 180)
    return np.array([[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]])


# @njit
def euler_zxz(phi, theta, psi):
    Rz1 = rotation_matrix_z(phi)
    Rx = rotation_matrix_x(theta)
    Rz2 = rotation_matrix_z(psi)
    return Rz1 @ Rx @ Rz2


# -------------------------------------------------------------------
# Gravitational field of source parallelepiped
# -------------------------------------------------------------------


# @njit
def gravitational_field_parallelepiped(
    xp,
    yp,
    zp,
    xc,
    yc,
    zc,
    lxs,
    lys,
    lzs,
    density,
    G,
):
    """
    Field generated by source parallelepiped.
    """

    x1 = xc - lxs / 2.0
    x2 = xc + lxs / 2.0

    y1 = yc - lys / 2.0
    y2 = yc + lys / 2.0

    z1 = zc - lzs / 2.0
    z2 = zc + lzs / 2.0

    xs = np.array([x1 - xp, x2 - xp])
    ys = np.array([y1 - yp, y2 - yp])
    zs = np.array([z1 - zp, z2 - zp])

    gx = 0.0
    gy = 0.0
    eps = 0

    for i in range(2):
        x = xs[i]

        for j in range(2):
            y = ys[j]

            for k in range(2):
                z = zs[k]

                # s = (-1) ** (i + j + k)
                s = (-1) ** (i + j + k + 1)  # Va el +1?

                r = np.sqrt(x * x + y * y + z * z) + eps

                gx += s * (
                    y * np.log(r + z + eps)
                    + z * np.log(r + y + eps)
                    - x * np.arctan2(y * z, x * r)
                    # - x * np.arctan(y * z / x * r)
                )

                gy += s * (
                    z * np.log(r + x + eps)
                    + x * np.log(r + z + eps)
                    - y * np.arctan2(x * z, y * r)
                    # - y * np.arctan(x * z / y * r)
                )

    gx *= G * density
    gy *= G * density

    return np.array([gx, gy])


# -------------------------------------------------------------------
# Torque integration
# -------------------------------------------------------------------


# # @njit
# def gravitational_torque_between_parallelepipeds(
#     # Observation/target body
#     xt,
#     yt,
#     zt,
#     lxt,
#     lyt,
#     lzt,
#     density_target,
#     # Orientation of target body
#     phi,
#     theta,
#     psi,
#     # Source body
#     xs,
#     ys,
#     zs,
#     lxs,
#     lys,
#     lzs,
#     density_source,
#     # Gravity
#     G,
#     # Numerical integration resolution
#     nx,
#     ny,
#     nz,
# ):
#     """
#     Computes gravitational torque around z axis on a target parallelepiped
#     due to a source parallelepiped.

#     Euler convention:
#         z(phi) -> new x(theta) -> new z(psi)

#     Returns
#     -------
#     Torque around z axis:
#     """

#     # Rotation matrix body -> world
#     R = euler_zxz(phi, theta, psi)

#     # Integration grid in body coordinates
#     x_local = np.linspace(-lxt / 2, lxt / 2, nx)
#     y_local = np.linspace(-lyt / 2, lyt / 2, ny)
#     z_local = np.linspace(-lzt / 2, lzt / 2, nz)

#     dx = lxt / (nx - 1)
#     dy = lyt / (ny - 1)
#     dz = lzt / (nz - 1)

#     dV = dx * dy * dz
#     dm = density_target * dV

#     torque = 0

#     for xl in x_local:
#         for yl in y_local:
#             for zl in z_local:
#                 # Position relative to target COM in body frame
#                 r_body = np.array([xl, yl, zl])

#                 # Transform to world frame
#                 r_world = R @ r_body
#                 # Absolute world position
#                 pos = np.array([xt, yt, zt]) + r_world
#                 # Gravitational field at this point
#                 g = gravitational_field_parallelepiped(
#                     pos[0], pos[1], pos[2], xs, ys, zs, lxs, lys, lzs, density_source, G
#                 )

#                 # Force on mass element
#                 dF = dm * g
#                 # Torque relative to target COM
#                 dTau = r_world[0] * dF[1] - r_world[1] * dF[0]

#                 torque += dTau


#     return torque
def gravitational_torque_between_parallelepipeds(
    # Observation/target body
    xt,
    yt,
    zt,
    lxt,
    lyt,
    lzt,
    density_target,
    # Orientation of target body
    phi,
    theta,
    psi,
    # Source body
    xs,
    ys,
    zs,
    lxs,
    lys,
    lzs,
    density_source,
    # Gravity
    G,
    nx,
    ny,
    nz,
    # Tolerances for scipy integration (optional but recommended)
    epsabs=1.49e-08,
    epsrel=1.49e-08,
):
    """Computes gravitational torque around z axis on a target parallelepiped

    due to a source parallelepiped using scipy.integrate.tplquad.

    Euler convention:
        z(phi) -> new x(theta) -> new z(psi)

    Returns
    -------
    Torque around z axis
    """

    # Rotation matrix body -> world
    R = euler_zxz(phi, theta, psi)

    # Define the integrand function for tplquad
    # Note: tplquad passes arguments in the order (z, y, x)
    def integrand(zl, yl, xl):
        # Position relative to target COM in body frame
        r_body = np.array([xl, yl, zl])

        # Transform to world frame
        r_world = R @ r_body

        # Absolute world position
        pos_x = xt + r_world[0]
        pos_y = yt + r_world[1]
        pos_z = zt + r_world[2]

        # Gravitational field at this point (per unit mass)
        g = gravitational_field_parallelepiped(
            pos_x,
            pos_y,
            pos_z,
            xs,
            ys,
            zs,
            lxs,
            lys,
            lzs,
            density_source,
            G,
        )

        # Force per unit volume: density * g
        dF_x = density_target * g[0]
        dF_y = density_target * g[1]

        # Torque per unit volume relative to target COM around world Z-axis
        dTau = r_world[0] * dF_y - r_world[1] * dF_x
        return dTau

    # Integration limits for the target body (centered around local origin)
    x_min, x_max = -lxt / 2, lxt / 2
    y_min, y_max = -lyt / 2, lyt / 2
    z_min, z_max = -lzt / 2, lzt / 2

    # tplquad takes limits functions for y and z, but since it's a
    # parallelepiped, the boundaries are constant scalars.
    torque, error = tplquad(
        integrand,
        x_min,
        x_max,
        lambda x: y_min,
        lambda x: y_max,
        lambda x, y: z_min,
        lambda x, y: z_max,
        epsabs=epsabs,
        epsrel=epsrel,
    )

    return torque


# @njit
def moment_of_inertia_two_parallelepipeds_z(
    density,
    lx,
    ly,
    lz,
    r,
):
    """
    Moment of inertia around the global z-axis for
    two identical rectangular parallelepipeds.

    Centers of mass:
        (+r, 0, 0)
        (-r, 0, 0)

    Parameters
    ----------
    density : float
        Density of parallelepipeds.

    lx, ly, lz : float
        Side lengths.

    r : float
        Distance of each center from origin along x.

    Returns
    -------
    Iz : float
        Total moment of inertia around z-axis.
    """
    mass = density * lx * ly * lz
    # Intrinsic inertia of one prism around its own COM
    Iz_cm = (mass / 12.0) * (lx**2 + ly**2)

    # Parallel axis theorem
    Iz_one = Iz_cm + mass * r**2

    # Two identical prisms
    Iz_total = 2.0 * Iz_one

    return Iz_total


# @njit
def d2t_phi(
    phi,
    phi_dot,
    # Densitiy,
    density,
    # Observation/target body
    r,
    lxt,
    lyt,
    lzt,
    # Source body
    xs,
    ys,
    zs,
    lxs,
    lys,
    lzs,
    # Numerical integration resolution
    nx,
    ny,
    nz,
    # Gravity
    G,
    # Pendulum parameters
    k,
    gamma,
    # Moment of inertia
    I,
):
    gravity_torque = (
        gravitational_torque_between_parallelepipeds(  # Observation/target body
            r * np.cos(phi * np.pi / 180),
            r * np.sin(phi * np.pi / 180),
            0,
            lxt,
            lyt,
            lzt,
            density,
            # Orientation of target body
            phi,
            0,
            0,
            # Source body
            xs,
            ys,
            zs,
            lxs,
            lys,
            lzs,
            density,
            # Gravity
            G,
            # Numerical integration resolution
            nx,
            ny,
            nz,
        )
    )
    return (-k * phi - gamma * phi_dot + gravity_torque) / I


# %%
# Funcion de evolucion con parámetros integrados
# @njit
def f(t, y):
    # Densitiy
    density = 11.34e3  # kg/m**3
    # Observation/target body
    r = 37e-2  # m
    lxt = 14e-2  # m
    lyt = 4e-2  # m
    lzt = 7e-2  # m
    # Distance between both cm at equilibrium
    d = 10e-2  # m, represents distance between both cm at equilibrium
    # Source body
    xs = r
    ys = d  # m
    zs = 0
    lxs = 15e-2  # m
    lys = 5e-2  # m
    lzs = 10e-2  # m
    # Numerical integration resolution
    nx = 10
    ny = 10
    nz = 10

    # Gravitiy
    G = 6.67430e-11
    G = 0
    # Pendulum parameters
    k = 0.007047886187862911  # De estimación
    gamma = 0
    # Moment of inertia
    I = moment_of_inertia_two_parallelepipeds_z(density, lxt, lyt, lzt, r)
    phi_dot_dot = d2t_phi(
        y[0],
        y[1],
        # Densitiy,
        density,
        # Observation/target body
        r,
        lxt,
        lyt,
        lzt,
        # Source body
        xs,
        ys,
        zs,
        lxs,
        lys,
        lzs,
        # Numerical integration resolution
        nx,
        ny,
        nz,
        # Gravity
        G,
        # Pendulum parameters
        k,
        gamma,
        # Moment of inertia
        I,
    )
    return np.array([y[1], phi_dot_dot])


phi_0 = 2
phi_dot_0 = 0
y0 = np.array([phi_0, phi_dot_0])
t = np.linspace(0, 200, 1000)
sol = solve_ivp(f, (t[0], t[-1]), y0, t_eval=t)
phi = sol.y[0]
plt.plot(t, phi, ".")


# %% Posicion de equilibrio
# @njit
def aceleracion(y):
    # Densitiy
    density = 11.34e3  # kg/m**3
    # Observation/target body
    r = 37e-2  # m
    lxt = 14e-2  # m
    lyt = 4e-2  # m
    lzt = 7e-2  # m
    # Distance between both cm at equilibrium
    d = 4e-2  # m, represents distance between both cm at equilibrium
    # Source body
    xs = r
    ys = d  # m
    zs = 0
    lxs = 15e-2  # m
    lys = 5e-2  # m
    lzs = 10e-2  # m
    # Numerical integration resolution
    nx = 20
    ny = 20
    nz = 20

    # Gravitiy
    G = 6.67430e-11
    # G = 0
    # Pendulum parameters
    # k = 0.007047886187862911  # De estimación
    k = 3e-5
    gamma = 0
    # Moment of inertia
    I = moment_of_inertia_two_parallelepipeds_z(density, lxt, lyt, lzt, r)
    phi_dot_dot = d2t_phi(
        y[0],
        0,
        # Densitiy,
        density,
        # Observation/target body
        r,
        lxt,
        lyt,
        lzt,
        # Source body
        xs,
        ys,
        zs,
        lxs,
        lys,
        lzs,
        # Numerical integration resolution
        nx,
        ny,
        nz,
        # Gravity
        G,
        # Pendulum parameters
        k,
        gamma,
        # Moment of inertia
        I,
    )
    return phi_dot_dot


eq = fsolve(aceleracion, 0)
print(eq)
