# %% Definir funciones
import numba as nb
import numpy as np
from scipy.constants import G as _G
from scipy.optimize import fsolve
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt


def moment_of_inertia_two_parallelepipeds_z(
    density,
    lx,
    ly,
    lz,
    r,
):
    """
    Moment of inertia around the global z-axis for
    two identical rectangular parallelepipeds.

    Centers of mass:
        (+r, 0, 0)
        (-r, 0, 0)

    Parameters
    ----------
    density : float
        Density of parallelepipeds.

    lx, ly, lz : float
        Side lengths.

    r : float
        Distance of each center from origin along x.

    Returns
    -------
    Iz : float
        Total moment of inertia around z-axis.
    """
    mass = density * lx * ly * lz
    # Intrinsic inertia of one prism around its own COM
    Iz_cm = (mass / 12.0) * (lx**2 + ly**2)

    # Parallel axis theorem
    Iz_one = Iz_cm + mass * r**2

    # Two identical prisms
    Iz_total = 2.0 * Iz_one

    return Iz_total


@nb.njit(fastmath=True)
def gravitational_field_parallelepiped(
    xp, yp, zp, xc, yc, zc, lxs, lys, lzs, density, G
):
    """
    Optimized field generated by source parallelepiped.
    """
    x1 = xc - lxs / 2.0
    x2 = xc + lxs / 2.0
    y1 = yc - lys / 2.0
    y2 = yc + lys / 2.0
    z1 = zc - lzs / 2.0
    z2 = zc + lzs / 2.0

    # Using tuples instead of np.array avoids heap allocation overhead in Numba
    xs_val = (x1 - xp, x2 - xp)
    ys_val = (y1 - yp, y2 - yp)
    zs_val = (z1 - zp, z2 - zp)

    gx = 0.0
    gy = 0.0

    for i in range(2):
        x = xs_val[i]
        for j in range(2):
            y = ys_val[j]
            for k in range(2):
                z = zs_val[k]

                # Fast sign determination
                s = 1.0 if (i + j + k) % 2 == 0 else -1.0
                r = np.sqrt(x * x + y * y + z * z)

                gx += s * (
                    y * np.log(r + z) + z * np.log(r + y) - x * np.arctan2(y * z, x * r)
                )
                gy += s * (
                    z * np.log(r + x) + x * np.log(r + z) - y * np.arctan2(x * z, y * r)
                )

    gx *= G * density
    gy *= G * density

    return gx, gy


@nb.njit(parallel=True, fastmath=True)
def calculate_torque_z(
    phi,
    r,
    lxs_p,
    lys_p,
    lzs_p,
    density_p,
    xc,
    yc,
    zc,
    lxs,
    lys,
    lzs,
    density,
    G,
    nodes,
    weights,
):
    """
    Calculates the z-axis torque on a transformed probe parallelepiped using
    Gauss-Legendre integration. Fully Numba JIT-able.
    """
    cos_phi = np.cos(phi)
    sin_phi = np.sin(phi)

    # Semi-axes sizes used to scale nodes/weights from [-1, 1] to the block limits
    hx = lxs_p / 2.0
    hy = lys_p / 2.0
    hz = lzs_p / 2.0

    num_pts = len(nodes)
    total_torque = 0.0

    # Parallelize the outer loop across available CPU cores
    for i in nb.prange(num_pts):
        u = hx * nodes[i]
        w_i = weights[i] * hx

        for j in range(num_pts):
            v = hy * nodes[j]
            w_j = weights[j] * hy

            for k in range(num_pts):
                w = hz * nodes[k]
                w_k = weights[k] * hz

                # 1. Rigid Transformation: Translate along x by 'r', then rotate by 'phi'
                # (Local block center starts at the origin)
                xp = (u + r) * cos_phi - v * sin_phi
                yp = (u + r) * sin_phi + v * cos_phi
                zp = w

                # 2. Get the gravitational field components at this point
                gx, gy = gravitational_field_parallelepiped(
                    xp, yp, zp, xc, yc, zc, lxs, lys, lzs, density, G
                )

                # 3. Torque density around z-axis: dTau = (x * g_y - y * g_x) * dm
                torque_density = (xp * gy - yp * gx) * density_p

                # 4. Accumulate weighted contribution
                total_torque += w_i * w_j * w_k * torque_density

    return total_torque


@nb.njit(parallel=True, fastmath=True)
def total_torque(
    phi, k, r, d, lxs_p, lys_p, lzs_p, lxs, lys, lzs, density, G, nodes, weights
):
    density_p = density
    xc = r
    yc = d
    zc = 0
    phi_scalar = phi[0]
    gravity_torque = calculate_torque_z(
        phi_scalar,
        r,
        lxs_p,
        lys_p,
        lzs_p,
        density_p,
        xc,
        yc,
        zc,
        lxs,
        lys,
        lzs,
        density,
        G,
        nodes,
        weights,
    )
    return -k * phi + gravity_torque


# @nb.njit(parallel=True, fastmath=True)
@nb.njit(fastmath=True)
def f(
    t,
    y,
    gamma,
    I,
    k,
    r,
    d,
    lxs_p,
    lys_p,
    lzs_p,
    lxs,
    lys,
    lzs,
    density,
    G,
    nodes,
    weights,
):
    density_p = density
    xc = r
    yc = d
    zc = 0
    phi = y[0]
    phi_dot = y[1]
    gravity_torque = calculate_torque_z(
        phi,
        r,
        lxs_p,
        lys_p,
        lzs_p,
        density_p,
        xc,
        yc,
        zc,
        lxs,
        lys,
        lzs,
        density,
        G,
        nodes,
        weights,
    )
    return np.array([phi_dot, (-k * phi - gamma * phi_dot + gravity_torque) / I])


# %% Definicion parámetros

# Problem parameters
k_actual = 0.007047886187862911  # Nuestro k de ahora
k_diego = 3.66e-5  # k de Diego estimado
k_prueba = 1e-4
k = k_prueba
r = 37e-2
d = 5e-2
lxs_p, lys_p, lzs_p = 14e-2, 4e-2, 7e-2
lxs, lys, lzs = 15e-2, 5e-2, 10e-2
density = 11340
G = _G
I = moment_of_inertia_two_parallelepipeds_z(density, lxs_p, lys_p, lzs_p, r)
gamma = 0

# Integration parameters
N_order = 10
nodes, weights = np.polynomial.legendre.leggauss(N_order)

# %% Posición de equilibriolxs
args = (k, r, d, lxs_p, lys_p, lzs_p, lxs, lys, lzs, density, G, nodes, weights)

equilibrium = fsolve(total_torque, 0, args=args) * 180 / np.pi
print(equilibrium)

# %% Simulación
ode_args = (
    gamma,
    I,
    k,
    r,
    d,
    lxs_p,
    lys_p,
    lzs_p,
    lxs,
    lys,
    lzs,
    density,
    G,
    nodes,
    weights,
)
phi_0 = 1
phi_dot_0 = 0
y0 = np.array([phi_0, phi_dot_0]) * np.pi / 180
t = np.linspace(0, 30 * 60, 1000)
sol = solve_ivp(f, (t[0], t[-1]), y0, t_eval=t, args=ode_args)
phi = sol.y[0] * 180 / np.pi
plt.plot(t, phi, ".")
